server {
    server_name visionarios.micasachurch.co;

    root /home/srdejo/apps/visionarios/frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://localhost:8089;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/visionarios.micasachurch.co/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/visionarios.micasachurch.co/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = visionarios.micasachurch.co) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name visionarios.micasachurch.co;
    return 404; # managed by Certbot


}
